name: GloomAI
main: ru.gloom.GloomAI

version: '${version}'
api-version: '1.16'

depend:
  - packetevents

softdepend:
  - WorldGuard

permissions:
  gloom.command.connect:
    description: Подключение сервера к личному кабинету Gloom
    default: op
